<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>fileTypes</key>
    <array>
      <string>ftl</string>
    </array>
    <key>scopeName</key>
    <string>source.ftl</string>
    <key>patterns</key>
    <array>
      <dict>
        <key>include</key>
        <string>#comment</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#message</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#wrong-line</string>
      </dict>
    </array>
    <key>repository</key>
    <dict>
      <key>comment</key>
      <dict>
        <key>name</key>
        <string>comment.fluent</string>
        <key>match</key>
        <string>^##?#?\s.*$</string>
      </dict>
      <key>message</key>
      <dict>
        <key>begin</key>
        <string>^(-?[a-zA-Z][a-zA-Z0-9_-]*\s*=\s*)</string>
        <key>end</key>
        <string>^(?=\S)</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>support.class.message-identifier.fluent</string>
          </dict>
        </dict>
        <key>contentName</key>
        <string>string.fluent</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#attributes</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#placeable</string>
          </dict>
        </array>
      </dict>
      <key>attributes</key>
      <dict>
        <key>begin</key>
        <string>\s*(\.[a-zA-Z][a-zA-Z0-9_-]*\s*=\s*)</string>
        <key>end</key>
        <string>^(?=\s*[^\.])</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>support.class.attribute-begin.fluent</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#placeable</string>
          </dict>
        </array>
      </dict>
      <key>placeable</key>
      <dict>
        <key>begin</key>
        <string>({)</string>
        <key>end</key>
        <string>(})</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.placeable.begin.fluent</string>
          </dict>
        </dict>
        <key>endCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.placeable.end.fluent</string>
          </dict>
        </dict>
        <key>contentName</key>
        <string>variable.other.placeable.content.fluent</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#placeable-string</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#placeable-function</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#placeable-reference-or-number</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#selector</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#invalid-placeable-wrong-placeable-missing-end</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#invalid-placeable-string-missing-end-quote</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#invalid-placeable-wrong-function-name</string>
          </dict>
        </array>
      </dict>
      <key>placeable-reference-or-number</key>
      <dict>
        <key>name</key>
        <string>variable.other.placeable.reference-or-number.fluent</string>
        <key>match</key>
        <string>((-|\$)[a-zA-Z0-9_-]+|[a-zA-Z][a-zA-Z0-9_-]*|[0-9]+)</string>
      </dict>
      <key>placeable-function</key>
      <dict>
        <key>begin</key>
        <string>([A-Z][A-Z0-9_-]*\()</string>
        <key>end</key>
        <string>(\))</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>support.function.placeable-function.call.begin.fluent</string>
          </dict>
        </dict>
        <key>endCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>support.function.placeable-function.call.end.fluent</string>
          </dict>
        </dict>
        <key>contentName</key>
        <string>string.placeable-function.fluent</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#function-comma</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#function-positional-argument</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#function-named-argument</string>
          </dict>
        </array>
      </dict>
      <key>function-comma</key>
      <dict>
        <key>name</key>
        <string>support.function.function-comma.fluent</string>
        <key>match</key>
        <string>,</string>
      </dict>
      <key>function-positional-argument</key>
      <dict>
        <key>name</key>
        <string>variable.other.function.positional-argument.fluent</string>
        <key>match</key>
        <string>\$[a-zA-Z0-9_-]+</string>
      </dict>
      <key>function-named-argument</key>
      <dict>
        <key>begin</key>
        <string>([a-zA-Z0-9]+:)\s*(["a-zA-Z0-9]+)</string>
        <key>end</key>
        <string>(?=\)|,|\s)</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>support.function.named-argument.name.fluent</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>variable.other.named-argument.value.fluent</string>
          </dict>
        </dict>
        <key>name</key>
        <string>variable.other.named-argument.fluent</string>
      </dict>
      <key>placeable-string</key>
      <dict>
        <key>begin</key>
        <string>(")(?=[^\n]*")</string>
        <key>end</key>
        <string>(")</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>variable.other.placeable-string-begin.fluent</string>
          </dict>
        </dict>
        <key>endCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>variable.other.placeable-string-end.fluent</string>
          </dict>
        </dict>
        <key>contentName</key>
        <string>string.placeable-string-content.fluent</string>
      </dict>
      <key>selector</key>
      <dict>
        <key>begin</key>
        <string>(-&gt;)</string>
        <key>end</key>
        <string>^(?=\s*})</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>support.function.selector.begin.fluent</string>
          </dict>
        </dict>
        <key>contentName</key>
        <string>string.selector.content.fluent</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#selector-item</string>
          </dict>
        </array>
      </dict>
      <key>selector-item</key>
      <dict>
        <key>begin</key>
        <string>(\s*\*?\[)([a-zA-Z0-9_-]+)(\]\s*)</string>
        <key>end</key>
        <string>^(?=\s|})</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>support.function.selector-item.begin.fluent</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>variable.other.selector-item.begin.fluent</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>support.function.selector-item.begin.fluent</string>
          </dict>
        </dict>
        <key>contentName</key>
        <string>string.selector-item.content.fluent</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#placeable</string>
          </dict>
        </array>
      </dict>
      <key>wrong-line</key>
      <dict>
        <key>match</key>
        <string>.*</string>
        <key>name</key>
        <string>invalid.illegal.wrong-line.fluent</string>
      </dict>
      <key>invalid-placeable-wrong-placeable-missing-end</key>
      <dict>
        <key>name</key>
        <string>invalid.illegal.wrong-placeable-missing-end.fluent</string>
        <key>match</key>
        <string>([^}A-Z]*$|[^-][^&gt;]$)\b</string>
      </dict>
      <key>invalid-placeable-string-missing-end-quote</key>
      <dict>
        <key>name</key>
        <string>invalid.illegal.wrong-placeable-missing-end-quote.fluent</string>
        <key>match</key>
        <string>"[^"]+$</string>
      </dict>
    </dict>
  </dict>
</plist>